name:  Deployment for Strapi API

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        
      - name: Setting up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-region: us-west-2 
      - name: Setting up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SURABHI_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa   

      - name:  Setting up the terraform
        uses: hashicorp/terraform-github-actions/init@v0.4.0
      - name: Initialization
        run: terraform init
        working-directory: ./Terraform
      - name: Apply the infrastructure
        run: terraform apply -auto-approve
        working-directory: ./Terraform
